name: Build APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Verify workspace structure
        run: |
          echo "Current directory:"
          pwd
          echo "Files in root:"
          ls -la
          echo "Checking for buildozer.spec:"
          ls -la buildozer.spec || echo "buildozer.spec not found!"
          echo "Checking for main.py:"
          ls -la main.py || echo "main.py not found!"

      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: ~/.buildozer
          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

      - name: Cache Buildozer local directory  
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: buildozer-local-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

      - name: Build APK with Buildozer
        run: |
          # Check current directory and files
          pwd
          ls -la
          
          # Verify buildozer.spec exists
          if [ ! -f "buildozer.spec" ]; then
            echo "ERROR: buildozer.spec not found in current directory!"
            echo "Creating a minimal buildozer.spec..."
            buildozer init
            # Copy our spec content
            if [ -f "buildozer.spec.bak" ]; then
              cp buildozer.spec.bak buildozer.spec
            fi
          fi
          
          # Show buildozer.spec content (first 20 lines)
          echo "=== buildozer.spec content ==="
          head -20 buildozer.spec
          echo "=============================="
          
          # Accept Android SDK licenses
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
          
          # Build the APK
          buildozer android debug

      - name: Find APK file
        id: find-apk
        run: |
          APK_FILE=$(find bin/ -name "*.apk" -type f | head -1)
          echo "apk-file=$APK_FILE" >> $GITHUB_OUTPUT
          echo "Found APK: $APK_FILE"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: cashlytics-apk
          path: ${{ steps.find-apk.outputs.apk-file }}
          if-no-files-found: error
