name: Build Cashlytics APK

on:
  push:
    branches: [ main ]
    paths: 
      - '**.py'
      - 'buildozer.spec'
      - 'requirements.txt'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: '9477386'
        packages: |
          platform-tools
          platforms;android-33
          build-tools;33.0.2
          ndk;25.2.9519653

    - name: Accept Android SDK licenses
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list_installed

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          ccache \
          zlib1g-dev \
          libffi-dev \
          libssl-dev \
          autoconf \
          libtool \
          pkg-config

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Cache Buildozer global directory
      uses: actions/cache@v3
      with:
        path: ~/.buildozer
        key: buildozer-global-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          buildozer-global-${{ runner.os }}-

    - name: Cache Buildozer dependencies
      uses: actions/cache@v3
      with:
        path: .buildozer
        key: buildozer-deps-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          buildozer-deps-${{ runner.os }}-

    - name: Build APK with Buildozer
      run: |
        # Set environment variables
        export ANDROID_HOME=$ANDROID_HOME
        export ANDROID_SDK_ROOT=$ANDROID_HOME
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
        
        # Debug: Show environment
        echo "ANDROID_HOME: $ANDROID_HOME"
        echo "PATH: $PATH"
        ls -la $ANDROID_HOME/
        
        # Accept licenses again before building
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
        
        # Build the APK
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: cashlytics-apk
        path: bin/*.apk
        retention-days: 30

    - name: Upload build logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-logs
        path: |
          .buildozer/android/platform/build-*/logs/
          .buildozer/android/platform/python-for-android/dists/*/build.log
        retention-days: 7
        if-no-files-found: ignore