name: Build APK (Docker)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Build APK using Docker
      run: |
        # Pull the latest Kivy buildozer Docker image
        docker pull kivy/buildozer:latest
        
        # Run buildozer in Docker container
        docker run --rm \
          -v ${{ github.workspace }}:/home/user/app \
          -w /home/user/app \
          kivy/buildozer:latest \
          bash -c "
            # Accept Android SDK licenses
            yes | \$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
            
            # Install additional Python packages
            pip install kivymd
            
            # Build the APK
            buildozer android debug
          "
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: cashlytics-apk-docker
        path: bin/*.apk
        retention-days: 30
        
    - name: List generated files
      run: |
        echo "Generated files:"
        find bin/ -name "*.apk" -exec ls -lh {} \; || echo "No APK files found"