name: Build APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build APK with Docker
        run: |
          # Create a temporary Dockerfile for buildozer
          cat > Dockerfile.buildozer << 'EOF'
          FROM kivy/buildozer:latest
          
          # Set working directory
          WORKDIR /app
          
          # Copy project files
          COPY . .
          
          # Update buildozer and accept licenses
          RUN buildozer android debug || echo "Build completed with warnings"
          EOF
          
          # Build Docker image
          docker build -f Dockerfile.buildozer -t cashlytics-builder .
          
          # Run container to build APK
          docker run --rm -v "$(pwd):/output" cashlytics-builder sh -c "
            cp -r /app/bin /output/ 2>/dev/null || echo 'No bin directory to copy'
            cp -r /app/.buildozer /output/ 2>/dev/null || echo 'No .buildozer directory to copy'
            find /app -name '*.apk' -exec cp {} /output/ \; 2>/dev/null || echo 'No APK files found'
            ls -la /output/
          "

      - name: Find APK file
        id: find-apk
        run: |
          echo "Looking for APK files..."
          ls -la
          APK_FILE=$(find . -name "*.apk" -type f | head -1)
          if [ -z "$APK_FILE" ]; then
            echo "No APK found, checking bin directory..."
            ls -la bin/ || echo "No bin directory"
            APK_FILE=$(find bin/ -name "*.apk" -type f 2>/dev/null | head -1)
          fi
          if [ -z "$APK_FILE" ]; then
            echo "ERROR: No APK file found!"
            exit 1
          fi
          echo "apk-file=$APK_FILE" >> $GITHUB_OUTPUT
          echo "Found APK: $APK_FILE"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: cashlytics-apk
          path: ${{ steps.find-apk.outputs.apk-file }}
          if-no-files-found: error
