name: Build APK (Proven Method)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Java 8
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-8-jdk
        echo "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> $GITHUB_ENV

    - name: Install system packages
      run: |
        sudo apt-get install -y \
          git \
          zip \
          unzip \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libffi-dev \
          libssl-dev

    - name: Setup Python environment
      run: |
        python -m pip install --upgrade pip
        pip install cython==0.29.36
        pip install buildozer==1.5.0

    - name: Use stable buildozer config
      run: |
        cp buildozer-stable.spec buildozer.spec
        echo "Using stable configuration:"
        grep -E "(android\.api|android\.ndk|requirements)" buildozer.spec

    - name: Accept Android licenses
      run: |
        mkdir -p "$HOME/.android/licenses"
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$HOME/.android/licenses/android-sdk-license"
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "$HOME/.android/licenses/android-sdk-license"
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$HOME/.android/licenses/android-sdk-license"

    - name: Clean previous builds
      run: |
        rm -rf .buildozer
        rm -rf bin

    - name: Build APK
      run: |
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
        export ANDROID_NDK_HOME=$HOME/.buildozer/android/platform/android-ndk-r23b
        
        yes | buildozer android debug

    - name: Find and copy APK
      run: |
        mkdir -p artifacts
        find . -name "*.apk" -exec cp {} artifacts/ \;
        ls -la artifacts/

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: cashlytics-apk-proven
        path: artifacts/*.apk